name: kingofthestonejungle
description: King of the Stone Jungle

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  http: ^0.12.1
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
